name: Run Tests

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "main"
      - "develop"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Dummy Sleep
        run: sleep 30

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
