name: Run Tests

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "main"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
